//
// Created by Krzysiek on 20.11.2018.
//

#ifndef TS3_BOT_CONFIG_H
#define TS3_BOT_CONFIG_H


#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 10011

#define DATABASE_IP "localhost"
#define DATABASE_USER "Taraj"
#define DATABASE_PASSWORD "123"
#define DATABASE "teamSpeak3"


#define TS3_SERVER_ADMIN_LOGIN "serveradmin"
#define TS3_SERVER_ADMIN_PASSWORD "123"
#define TS3_SERVER_ID 1

#define TS3_BOT_REFRESH_TIME 1 //sek
#define TS3_BOT_DATA_PACKAGE_SIZE 1024
#define TS3_BOT_NAME "Bot"


#define TS3_ALLOW_RECORDING_GROUP "15"


#define TS3_MIN_AFK_TIME 1200000 // sek * 1000
#define TS3_AFK_GROUP "14"


#define TS3_HELPER_IGNORE_GROUP "40"
#define TS3_HELPER_GROUP "12"
#define TS3_HELPER_CHANNEL "3"


#define TS3_CREATE_CHANNEL_GROUP "16"
#define TS3_CHANNEL_ADMIN_GROUP "5"
#define TS3_CHANNEL_DEFAULT_PASSWORD "123"


#define TS3_RANKING_CONNECTION_TIME_CHANNEL_ID "31"
#define TS3_RANKING_CONNECTION_COUNT_CHANNEL_ID "29"
#define TS3_RANKING_LONGEST_CONNECTION_CHANNEL_ID "13"

#define TS3_BOT_CONFIG_H

#endif //TS3_BOT_CONFIG_H
